경로 데이터 관리자 initial commit
WAVEM-Inc/path_graph_data pull request #1
Opened 2024-03-22 06:22 UTC by yskwonwm

## 개요

KEC 자율 주행 차량에서 사용되는 주행 경로 및  그래프 정보를 저장하고 관리 하는 패키지.

아래와 같이 서비스 서버 패키지 와 서비스 메시지 패키지로 구성되어 있다.
- path_graph_msgs
path 서비스와 graph 서비스를 등록한다.
- path_storage
등록된 서비스에 따라 서비스를 제공하는 서비스 서버이다.

세부 내용은 [README.md](https://github.com/WAVEM-Inc/path_graph_data/blob/KEC/Humble/Feature/yskwon/path_storage_manager/README.md)  참조

## PR Type

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정/삭제
- [ ] 기타

## PR Checklist

- [x] commit message Conventions에 맞게 작성했습니다.: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit 
- [x] 변경 사항에 대한 테스트를 했습니다.
- [x] Coding Conventions에 맞게 작성했습니다.

## breaking change?

- [ ] Yes
- [x] No

## Other information

2024-03-22 06:26 UTC, Anchangun requested changes
msg에 route_msgs 내용이 중복으로 들어가 있어 변경 요청 드립니다.

2024-03-22 06:27 UTC, BaeMinSeok9202 approved these changes
RGTM

2024-03-25 01:37 UTC, reidlo5135 reviewed
- 질문 사항
1. pip로 설치한 파이썬 모듈이 있는 지
2. 또한, 있다면 requirements.txt 같은 파일이 있는 지(존재 시, "pip install -r requirements.txt 로 일괄 설치 가능)

2024-03-25 02:21 UTC, NTques commented
path_graph_msgs의 상속성에 대한 기재 필요.
ReadME.md에 route_msgs에 대한 상속성 기재 혹은 route_msgs install & build 가이드 기재 요청드립니다.

CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "Findroute_msgs.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "route_msgs", but CMake did not find one.


  Could not find a package configuration file provided by "route_msgs" with
  any of the following names:


    route_msgsConfig.cmake
    route_msgs-config.cmake


  Add the installation prefix of "route_msgs" to CMAKE_PREFIX_PATH or set
  "route_msgs_DIR" to a directory containing one of the above files.  If
  "route_msgs" provides a separate development package or SDK, be sure it has
  been installed.

2024-03-25 02:34 UTC, NTques reviewed
ros2 launch path_storage path_storage.launch.py로 실행 시 아래의 에러 발생.

~~~
[INFO] [launch]: All log files can be found below /home/antique/.ros/log/2024-03-25-11-31-45-969963-antique-7983

[INFO] [launch]: Default logging verbosity is set to INFO

[INFO] [path_storage_manager-1]: process started with pid [7984]

[path_storage_manager-1] [INFO] [1711333906.397251138] [path_storage_manager]: Start storage path data management service

[path_storage_manager-1] Traceback (most recent call last):

[path_storage_manager-1]   File "/home/antique/ros2_ws/install/path_storage/lib/path_storage/path_storage_manager", line 33, in <module>

[path_storage_manager-1]     sys.exit(load_entry_point('path-storage==0.0.0', 'console_scripts', 'path_storage_manager')())

[path_storage_manager-1]   File "/home/antique/ros2_ws/install/path_storage/lib/python3.10/site-packages/path_storage/main.py", line 8, in main

[path_storage_manager-1]     service = PathService()

[path_storage_manager-1]   File "/home/antique/ros2_ws/install/path_storage/lib/python3.10/site-packages/path_storage/service/pathService.py", line 35, in __init__

[path_storage_manager-1]     path_topic = conf.config["CONFIG"]["path_topic"]

[path_storage_manager-1]   File "/usr/lib/python3.10/configparser.py", line 965, in __getitem__

[path_storage_manager-1]     raise KeyError(key)

[path_storage_manager-1] KeyError: 'CONFIG'

[ERROR] [path_storage_manager-1]: process has died [pid 7984, exit code 1, cmd '/home/antique/ros2_ws/install/path_storage/lib/path_storage/path_storage_manager --ros-args --log-level info --ros-args -r __node:=path_storage_manager'].
~~~

2024-03-25 03:07 UTC, yskwonwm commented
아래 사항 반영해서 다시  PR 요청 하겠습니다.

1. 불필요한  route_msgs 내용 삭제 
2. pip 로 설치한 파이썬 모듈 확인 - requirements.txt 파일 추가

2024-03-25 03:20 UTC, closed without merging